// Team data with players and coaches
export const teamsData = [
  {
    id: 1,
    name: "Alliance Black State League 1 Mens",
    slug: "mens-sl1m-black",
    image: "/placeholder.svg?height=600&width=800",
    description: "Competing in State League 1, Alliance Black represents the elite of our men's division.",
    schedule: "Matches every Friday evening",
    achievements: ["Regional Champions 2024", "National Quarter-Finalists 2023"],
    coaches: [
      {
        id: 1,
        name: "John Smith",
        role: "Head Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Former national team player with over 15 years of coaching experience.",
      },
      {
        id: 2,
        name: "Michael Davis",
        role: "Assistant Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Specializes in technical skills and defensive strategies.",
      },
    ],
    players: [
      {
        id: 1,
        name: "Benson Lin",
        number: 1,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 2,
        name: "Cayden Scanlon",
        number: 2,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 3,
        name: "Timothy Chee",
        number: 3,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 4,
        name: "Patrick Dumiter",
        number: 7,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 5,
        name: "Matthew Chen",
        number: 48,
        position: "Opposite",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 6,
        name: "Matthew Wong",
        number: 17,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 7,
        name: "Caleb Lau",
        number: 30,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 8,
        name: "Brendan Leung",
        number: 34,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 10,
        name: "Paul Wong",
        number: 48,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 11,
        name: "Amos Woon",
        number: 49,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 12,
        name: "Patrick Cirdei",
        number: 68,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 13,
        name: "Chamnan Dy",
        number: 80,
        position: "Opposite",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 14,
        name: "Jiunn Chua",
        number: 14,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
    ],
  },
  {
    id: 2,
    name: "Men's Reserve 2",
    slug: "mens-reserve-2",
    image: "/placeholder.svg?height=600&width=800",
    description: "Competitive men's team focused on player development and advancement.",
    schedule: "Matches every Saturday afternoon",
    achievements: ["Division 2 Runners-up 2024"],
    coaches: [
      {
        id: 3,
        name: "William Johnson",
        role: "Head Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Experienced coach with a focus on developing young talent.",
      },
    ],
    players: [
      {
        id: 11,
        name: "Kevin Clark",
        number: 3,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: true,
      },
      {
        id: 12,
        name: "Brian Lewis",
        number: 6,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 13,
        name: "Jason Walker",
        number: 14,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 14,
        name: "Eric Robinson",
        number: 1,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 15,
        name: "Mark Wilson",
        number: 13,
        position: "Opposite Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 16,
        name: "Steven Garcia",
        number: 17,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 17,
        name: "Paul Martinez",
        number: 21,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 18,
        name: "George Thompson",
        number: 8,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
    ],
  },
  {
    id: 3,
    name: "Women's Reserve 1",
    slug: "womens-reserve-1",
    image: "/placeholder.svg?height=600&width=800",
    description: "Elite women's team competing at the highest level of regional volleyball.",
    schedule: "Matches every Friday evening",
    achievements: ["Regional Champions 2023, 2024", "National Semi-Finalists 2023"],
    coaches: [
      {
        id: 4,
        name: "Sarah Johnson",
        role: "Head Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Former professional player with extensive coaching experience at the national level.",
      },
      {
        id: 5,
        name: "Jennifer Williams",
        role: "Assistant Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Specializes in offensive strategies and player development.",
      },
    ],
    players: [
      {
        id: 19,
        name: "Emily Davis",
        number: 5,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: true,
      },
      {
        id: 20,
        name: "Jessica Wilson",
        number: 8,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 21,
        name: "Amanda Thompson",
        number: 12,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 22,
        name: "Samantha Brown",
        number: 2,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 23,
        name: "Olivia Martinez",
        number: 7,
        position: "Opposite Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 24,
        name: "Sophia Taylor",
        number: 10,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 25,
        name: "Emma Johnson",
        number: 4,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 26,
        name: "Ava Williams",
        number: 9,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 27,
        name: "Mia Garcia",
        number: 1,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 28,
        name: "Isabella Robinson",
        number: 11,
        position: "Opposite Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
    ],
  },
  {
    id: 4,
    name: "Women's Reserve 2",
    slug: "womens-reserve-2",
    image: "/placeholder.svg?height=600&width=800",
    description: "Competitive women's team with a focus on tactical development and teamwork.",
    schedule: "Matches every Saturday afternoon",
    achievements: ["Division 2 Champions 2024"],
    coaches: [
      {
        id: 6,
        name: "Emily Davis",
        role: "Head Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Former collegiate player with a passion for developing young talent.",
      },
    ],
    players: [
      {
        id: 29,
        name: "Charlotte Lewis",
        number: 6,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: true,
      },
      {
        id: 30,
        name: "Abigail Clark",
        number: 3,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 31,
        name: "Harper Walker",
        number: 14,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 32,
        name: "Ella Robinson",
        number: 1,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 33,
        name: "Scarlett Wilson",
        number: 13,
        position: "Opposite Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 34,
        name: "Grace Garcia",
        number: 17,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 35,
        name: "Lily Martinez",
        number: 21,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 36,
        name: "Chloe Thompson",
        number: 8,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
    ],
  },
  {
    id: 5,
    name: "Boys U17",
    slug: "boys-u17",
    image: "/placeholder.svg?height=600&width=800",
    description: "Youth development team for boys under 17, focusing on core skills and game understanding.",
    schedule: "Training twice weekly, matches on Saturdays",
    achievements: ["Youth League Champions 2024"],
    coaches: [
      {
        id: 7,
        name: "Robert Taylor",
        role: "Head Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Specializes in youth development with a focus on fundamentals and teamwork.",
      },
      {
        id: 8,
        name: "Daniel Harris",
        role: "Assistant Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Former youth national team player with a passion for developing young talent.",
      },
    ],
    players: [
      {
        id: 37,
        name: "Noah Johnson",
        number: 5,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: true,
      },
      {
        id: 38,
        name: "Liam Wilson",
        number: 8,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 39,
        name: "Mason Thompson",
        number: 12,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 40,
        name: "Ethan Brown",
        number: 2,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 41,
        name: "Lucas Martinez",
        number: 7,
        position: "Opposite Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 42,
        name: "Logan Taylor",
        number: 10,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 43,
        name: "Jackson Johnson",
        number: 4,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 44,
        name: "Aiden Williams",
        number: 9,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 45,
        name: "Caleb Garcia",
        number: 1,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
    ],
  },
  {
    id: 6,
    name: "Girls U17",
    slug: "girls-u17",
    image: "/placeholder.svg?height=600&width=800",
    description: "Youth development team for girls under 17, building the next generation of volleyball talent.",
    schedule: "Training twice weekly, matches on Saturdays",
    achievements: ["Youth Tournament Winners Spring 2024"],
    coaches: [
      {
        id: 9,
        name: "Amanda Wilson",
        role: "Head Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Former collegiate player with a passion for developing young female athletes.",
      },
    ],
    players: [
      {
        id: 46,
        name: "Sophia Johnson",
        number: 5,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: true,
      },
      {
        id: 47,
        name: "Olivia Wilson",
        number: 8,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 48,
        name: "Emma Thompson",
        number: 12,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 49,
        name: "Ava Brown",
        number: 2,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 50,
        name: "Isabella Martinez",
        number: 7,
        position: "Opposite Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 51,
        name: "Mia Taylor",
        number: 10,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 52,
        name: "Charlotte Johnson",
        number: 4,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 53,
        name: "Amelia Williams",
        number: 9,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 54,
        name: "Harper Garcia",
        number: 1,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
    ],
  },
  {
    id: 7,
    name: "Reserve 3 Gold",
    slug: "res-3-gold",
    image: "/placeholder.svg?height=600&width=800",
    description: "Our special Reserve 3 Gold team competing in regional tournaments.",
    schedule: "Matches every Sunday afternoon",
    achievements: ["Tournament Champions Winter 2024", "Most Improved Team 2023"],
    coaches: [
      {
        id: 10,
        name: "Richard Adams",
        role: "Head Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Experienced coach with a focus on team building and competitive strategy.",
      },
      {
        id: 11,
        name: "Laura Phillips",
        role: "Assistant Coach",
        image: "/placeholder.svg?height=400&width=400",
        bio: "Former professional player specializing in technical skill development.",
      },
    ],
    players: [
      {
        id: 55,
        name: "Alex Morgan",
        number: 7,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: true,
      },
      {
        id: 56,
        name: "Jordan Taylor",
        number: 10,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: true,
      },
      {
        id: 57,
        name: "Casey Johnson",
        number: 4,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 58,
        name: "Riley Smith",
        number: 2,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 59,
        name: "Taylor Wilson",
        number: 8,
        position: "Opposite Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 60,
        name: "Jamie Davis",
        number: 12,
        position: "Middle Blocker",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 61,
        name: "Quinn Roberts",
        number: 5,
        position: "Outside Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 62,
        name: "Avery Martin",
        number: 9,
        position: "Setter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 63,
        name: "Cameron White",
        number: 15,
        position: "Libero",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
      {
        id: 64,
        name: "Drew Parker",
        number: 11,
        position: "Opposite Hitter",
        image: "/placeholder.svg?height=400&width=400",
        isCaptain: false,
      },
    ],
  },
]

// Helper function to get a team by slug
export function getTeamBySlug(slug: string) {
  return teamsData.find((team) => team.slug === slug)
}

// Helper function to get teams by category
export function getTeamsByCategory(category: "mens" | "womens" | "youth" | "all") {
  if (category === "all") return teamsData

  if (category === "mens") {
    return teamsData.filter((team) => team.name.includes("Men"))
  }

  if (category === "womens") {
    return teamsData.filter((team) => team.name.includes("Women"))
  }

  if (category === "youth") {
    return teamsData.filter((team) => team.name.includes("U17"))
  }

  return []
}
